[env:rp2040_swd]
platform = raspberrypi
board = rpipico
framework = arduino
monitor_speed = 115200

upload_protocol = cmsis-dap
debug_tool = cmsis-dap

build_flags =
    -D PICO_SCAN_I2C_FOR_WIRE
    -I src