[env:rp2040_usb]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.usb_product = "Secfest 2026 Badge"
monitor_speed = 115200

upload_protocol = picotool

lib_deps =
    adafruit/Adafruit IS31FL3731 Library
    adafruit/Adafruit BusIO

build_flags =
    -D PICO_SCAN_I2C_FOR_WIRE
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I src
